---
title: "FAQ"
---


#### Projects

- Is there a project component in the course?
    - Yes and No. We will have a project-like question in each of your assignments. This will be a more "structured" project in that sense and all students would have the same question. However, there is no separate project component in the course. We feel this will help you get a better understanding of the concepts covered in the course, and the added structure will help you get started with the project.

- Can you give an example of the project question?
    - Sure. We will build an activity classifier: walking, running, etc. Initially, we use publicly available datasets to build the classifier. We will then help you with collecting your data using your smartphone and build a classifier using your data. Those who want to go beyond the learning objectives, can deploy the classifier on your smartphone.

---

#### Prerequisites

- What are the course prerequisites?
    - The course has no "formal" prerequisites like all courses at IITGn. However, it is assumed that you have a basic understanding of: 
        - programming (Python), and data structures (ES242 equivalent)
        - probability and statistics 
        - linear algebra 
        - calculus 
- What is the prerequisite exam?
    - This is an exam that we have designed to ensure that you have the necessary background to take the course.
- How can I prepare for the prerequisite exam?
    - Your UG course material should be sufficient to prepare for the exam.
    - You may additionally refer to the "prerequisite" reading section on the [course homepage](./index.html).
- What happens if I do not clear the prerequisite exam?
    - You will not be allowed to take the course.
- What do you mean by "clear" the exam?
    - Like all courses at IITGn, the instructor will decide the cut-off for the exam. You will have to score above the cut-off to clear the exam. No cut-off will be revealed to the students apriori.

---

#### Laptop policy

- Can I use my laptop in the class?
    - No. You are not allowed to use your laptop in the class for any reason.

#### Quizzes

- What happens if I miss a quiz due to any reason?
    - The quiz will be marked as 0.
    - The provision of best 3 out of 4 quizzes is designed keeping in mind such scenarios.
- Will the quizzes and end-semester exam be open book? Will I be allowed to carry notes?
    - No, the exams and quizzes will be closed book. You are not permitted to carry notes.
- How soon can I expect to receive my answer sheets back?
    - You should expect to receive answer sheets back in 4-5 working days.
- Is there an end-semester exam or mid-semester exam?
    - 2 out of the 4 quizzes will be held in the mid-semester and end-semester slots. The remaining two quizzes will be held during the semester.
- Will the quizzes be MCQs or subjective?
    - The quizzes may contain both the MCQs and subjective questions.
---

#### Assignments
- What happens if I miss an assignment due to any reason?
    - There will no extensions for assignments.
- I have a doubt in the assignment. Whom should I write to?
    - Ask on the slack #assignments channel. If you don't get a response within 2 days, write to the course instructor.
- I do not know Python. Can I code assignments in some other language?
    - Unfortunately, no. You have to stick to Python.
- How will you evaluate the assignment?
    - The assignments would be followed by a viva. The TAs would first check the code and compare against the submission. Any change from the submitted code is not allowed and any instance of the same would culminate in a warning. The TAs would run the code and ask a few questions. About 75% of these questions would be based on the assignment in question and about 25% would be based on the theory behind the concepts covered in the assignment. 
    - The grade breakup would be: i) code runs correctly and solves the problem [50% marks]; ii) questions based on the assignment and student understanding of code [25% marks]; iii) code quality [12.5% marks]; iv) questions based on the theory behind the concepts covered in the assignments [12.5% marks]
- Is the assignment individual or group?
    - The assignment is group. In case of group, all team members get the same grade for the assignment.

---

#### Attendance

- Attendance policy
    - Attendance is mentioned in the grading policy clearly.  

---

#### Audit policy

You are free to attend the lectures. However, given the limited number of TAs and the large number of students, we will not be able to grade your submissions. You can not formally contribute to any team in their assignments. 

---

#### Computational resources

Typically, we have been kindly provided with Google Cloud credits. We will update this section once we have the credits. Once you get these credits, you can use them for your assignments. They are more than sufficient for the assignments. 


