---
title: "Grading Policy"
---


- Quizzes: 54%
    - 18% each
    - Best 3 out of 4
    - If you miss a single quiz for any reason, there will be no makeups
---

- Assignments: 40%
    - 4 or 5 assignments
    - Done in groups of TBA
    - Atleast one question per assignment will be a project-like question
    - Variable weight (e.g. some assignments would be 10%, some 12%, etc.)
    - Some assignments would involve:
        - Making pull requests to public repositories
        - Writing Hugging Face Spaces like demos
---

- Attendance: 6%
    - <= 3 absences: 6%
    - 4 or 5 absences: 5%
    - 6 or 7 absences: 4%
    - 8 or 9 absences: 3%
    - 10 or 11 absences: 2%
    - 12 or more absences: 0%

Here is the [leave form](https://docs.google.com/forms/d/1efg5pt10GssAmyxIF83reFc5rQslRH4mI-yng7XXZ78/edit) for the class. Please fill it out if you are going to miss a class. Also, write an email to TA Isha Narang to check the status of your leave request.

---

BONUS (above 100%)

- Kaggle like competition bonus: (subject to change)
    - 80th percentile: 1%
    - 95th percentile: 3%
    - Top three: 5%

---

- Upto 4% extra marks for answering questions in classes. Each question will be worth 0.5%. Thus, a student can avail this a maximum of 8 times. It is upto the discretion of the instructor to award these marks.








