---
title: "Schedule"
---

::: {.callout-tip}
## Summary

* [Github repo containing source code for lectures and notebooks](https://github.com/nipunbatra/ml-teaching)
* [PDF Lecture slides](https://nipunbatra.github.io/ml-teaching/slides.html)
* [Rendered Lecture notebooks](https://nipunbatra.github.io/ml-teaching/notebooks.html)
* [YouTube playlist containing recodings](https://www.youtube.com/playlist?list=PLftoLyLEwECDqanAL7LkZNnZG9VdNCiJF)

:::


| Lecture # |    Date     | Topic (Slides)                                  | Notebooks | YouTube Recording | Reading |
| :-------: | :---------: | :---------------------------------------------- | :-------: | --------- | ------- |
|     0     | 30 Dec 2023 | [Pre-requisite quiz released](exams/prereq.qmd) |           |           |         |
|     1     |    3 Jan    | [Introduction and Logistics](https://nipunbatra.github.io/ml-teaching/slides/1-introduction-ml.pdf)                      |      [Transcription and local LLMs](https://nipunbatra.github.io/ml-teaching/notebooks/transcript.html), [Segmentation and Localization](https://nipunbatra.github.io/ml-teaching/notebooks/object-detection-segmentation.html), [Prompt to Image](https://nipunbatra.github.io/ml-teaching/notebooks/text_to_image.html)     |      [Recording](https://www.youtube.com/watch?v=XuDrvFmvk2U)     |         |
| 2| 5 Jan| [Convention, Metrics, Classification, Regression](https://nipunbatra.github.io/ml-teaching/slides/accuracy_convention.pdf)|[Rule based vs ML](https://nipunbatra.github.io/ml-teaching/notebooks/rule-based-vs-ml.html), [Confusion Matrix](https://nipunbatra.github.io/ml-teaching/notebooks/confusion-mnist.html), [Dummy baselines](https://nipunbatra.github.io/ml-teaching/notebooks/dummy-baselines.html)|[Recording](https://www.youtube.com/watch?v=WUfduFsodE0)||
| 3| 8 Jan| [Decision Trees 1](https://nipunbatra.github.io/ml-teaching/slides/decision-trees.pdf)|[Entropy](https://nipunbatra.github.io/ml-teaching/notebooks/entropy.html), [Decision Trees Real Output](https://nipunbatra.github.io/ml-teaching/notebooks/decision-tree-real-output.html), [DT Real Input Discrete Output](https://nipunbatra.github.io/ml-teaching/notebooks/decision-tree-real-input-discrete-output.html)|[Recording](https://www.youtube.com/watch?v=Bc6p3Yxgo7c)||
| 4| 10 Jan| [Decision Trees 2, Bias and Variance](https://nipunbatra.github.io/ml-teaching/slides/bias-variance.pdf)|[Bias variance](https://nipunbatra.github.io/ml-teaching/notebooks/bias-variance.html), [Decision Trees + Overfitting, Underfitting](https://nipunbatra.github.io/ml-teaching/notebooks/decision-tree-real-input-real-output.html)| [Recording](https://www.youtube.com/watch?v=zqNj-B78i_0)||
|5| 12 Jan| Tutorial on Numpy, Pandas, Classes, [Cross-validation](https://nipunbatra.github.io/ml-teaching/slides/cross-validation.pdf)| [Numpy, Pandas, Entropy](https://nipunbatra.github.io/ml-teaching/notebooks/numpy-pandas-basics.html), [Classes and Trees](https://nipunbatra.github.io/ml-teaching/notebooks/classes-trees.html), [Cross-validation and tuning hyperparameters](https://nipunbatra.github.io/ml-teaching/notebooks/hyperparams-experiments.html)| [Tutorial recording](https://www.youtube.com/watch?v=P980btm9C3c), [Lecture on Cross-validation](https://www.youtube.com/watch?v=GP4XW8wzPM8)||
|6| 15 Jan| Cross-validation, [Ensemble Methods](https://nipunbatra.github.io/ml-teaching/slides/ensemble.pdf)| [Cross-validation and tuning hyperparameters](https://nipunbatra.github.io/ml-teaching/notebooks/hyperparams-experiments.html)| [Recording](https://www.youtube.com/watch?v=FrNR-1cfpHc)||
|7| 17 Jan| [Lecture on Random Forests](https://nipunbatra.github.io/ml-teaching/slides/ensemble.pdf)|, Tutorial on Random Forests + Meshgrid |[Video](https://www.youtube.com/watch?v=NDYiYk7vJTU)|[Notebook on Random Forests feature importance from scratch](https://nipunbatra.github.io/ml-teaching/notebooks/ensemble-feature-importance.html), [Notebook on meshgrid](https://nipunbatra.github.io/ml-teaching/notebooks/meshgrid.html)||
|8| 19 Jan| [Linear Regression](https://nipunbatra.github.io/ml-teaching/slides/linear-regression.pdf)|[Recording](https://www.youtube.com/watch?v=3cAzgZOrC3U)|||
|9| 24 Jan| [Linear Regression: Basis Functions](https://nipunbatra.github.io/ml-teaching/slides/linear-regression.pdf)|[Recording](https://www.youtube.com/watch?v=gkb9-xJfR08)|[Notebook](https://nipunbatra.github.io/ml-teaching/notebooks/basis.html)||
|10| 25 Jan| [Linear Regression: Geometric Interpretation](https://nipunbatra.github.io/ml-teaching/slides/linear-regression.pdf)|[Recording](https://www.youtube.com/watch?v=SE0WhKNd8K8)|[Notebook](https://nipunbatra.github.io/ml-teaching/notebooks/geometric-linear-regression.html)||
10|  27 Jan| [Multi-colinearity, Dummy Variables](https://nipunbatra.github.io/ml-teaching/slides/linear-regression.pdf)|[Recording](https://www.youtube.com/watch?v=htXMbi-G5HQ) | [Notebook](https://nipunbatra.github.io/ml-teaching/notebooks/dummy-variables-multi-colinearity.html)| |
11| 29 Jan | [Gradient Descent](https://nipunbatra.github.io/ml-teaching/slides/gradient-descent.pdf) |[Recording](https://www.youtube.com/watch?v=3BJfkVM1R9A) | [Notebook on Taylor's series](https://nipunbatra.github.io/ml-teaching/notebooks/taylor.html), [Notebook on Contour plots and gradient descent](https://nipunbatra.github.io/ml-teaching/notebooks/contour.html)| |
12| 31 Jan| Tutorial on GCloud + Forecasting + Polynomial Regression with Basis functions | | [Notebook on Polynomial Regression](https://nipunbatra.github.io/ml-teaching/notebooks/polynomial_features.html), [Notebook on Autoregressive Model](https://nipunbatra.github.io/ml-teaching/notebooks/autoregressive_model.html)| [Article on Polynomial Regression](https://alexshtf.github.io/2024/01/21/Bernstein.html)|
13| 2 Feb| Quiz 1 | | | |
14| 5 Feb | [Gradient Descent](https://nipunbatra.github.io/ml-teaching/slides/gradient-descent.pdf) | [Recording](https://www.youtube.com/watch?v=GoGnoqkITjs) | [Notebook on Gradient Descent](https://nipunbatra.github.io/ml-teaching/notebooks/gd.html) | |
15| 7 Feb| [Movie recommendation, Matrix Factorisation](https://nipunbatra.github.io/ml-teaching/slides/MovieRecommendation.pdf)|[Recording](https://www.youtube.com/watch?v=zf1e3HhLriM)|[Notebook on Movie Recommendation](https://nipunbatra.github.io/ml-teaching/notebooks/movie-recommendation-knn-mf.html)||
16| 9 Feb| Regularised Linear Regression: [Ridge Regression](https://nipunbatra.github.io/ml-teaching/slides/ridge-regression.pdf), [LASSO Regression](https://nipunbatra.github.io/ml-teaching/slides/lasso-regression.pdf)|[Recording](https://youtu.be/Jn4dMLGSZuQ?si=WoHlG7xm28FonD-I) | | |
17| 12 Feb| [Coordinate Descent](https://nipunbatra.github.io/ml-teaching/slides/lasso-regression.pdf) + [Time Complexity](https://nipunbatra.github.io/ml-teaching/slides/time_complexity.pdf) + [ML Maths](https://nipunbatra.github.io/ml-teaching/slides/ml-maths.pdf) + [Convexity](https://nipunbatra.github.io/ml-teaching/slides/convexity.pdf)| Not Recorded | [Notebook on Sklearn with GPU](https://nipunbatra.github.io/ml-teaching/notebooks/Sklearn_on_GPU.html)| |
18| 14 Feb| [Mock Quiz](https://nipunbatra.github.io/ml-teaching/slides/mock-quiz.pdf)| | | |
19| 16 Feb| Guest Lecture by [Arjun Bhagoji](https://arjunbhagoji.github.io/), [Adversarial Examples for ML](https://nipunbatra.github.io/ml-teaching/slides/guest-lecture.pdf)| |[Notebook](https://nipunbatra.github.io/ml-teaching/notebooks/guest-lecture/Student_copy_adv_examples_tutorial__Arjun_Bhagoji.html) | |
20| 26 Feb| Mid sem exam discussion | | | |
21| 28 Feb| [Logistic Regression](https://nipunbatra.github.io/ml-teaching/slides/logistic-1.pdf)|[Recording](https://www.youtube.com/watch?v=vMlOUAys38Q)|[Notebook on why use logits](https://nipunbatra.github.io/ml-teaching/notebooks/logits-usage.html), [Notebook on Logistic regression in Torch](https://nipunbatra.github.io/ml-teaching/notebooks/logistic-regression-torch.html)| |
22| 1 March| [Logistic Regression](https://nipunbatra.github.io/ml-teaching/slides/logistic-1.pdf)|[Recording](https://www.youtube.com/watch?v=oD8EnYTYdpk)|[Notebook](https://nipunbatra.github.io/ml-teaching/notebooks/logistic-circular.html)| |
23| 5 March| [MLP I](https://nipunbatra.github.io/ml-teaching/slides/mlp.pdf) |[Recording](https://www.youtube.com/watch?v=eWGDS4nvd_w)|| |
24| 6 March| [MLP II](https://nipunbatra.github.io/ml-teaching/slides/mlp.pdf)|[Recording](https://www.youtube.com/watch?v=qPXJNgSYcXA)|[Notebook](https://nipunbatra.github.io/ml-teaching/notebooks/nn_vectorization_with_vmap_jaxtyping_and_beartype_zeel.html#vectorization-with-torch.vmap)| |
25| 7 March| [Next token prediction](https://nipunbatra.github.io/ml-teaching/slides/next-token.pdf) |[Recording](https://www.youtube.com/watch?v=RTRuN0GgQo4&feature=youtu.be)|[Notebook](https://nipunbatra.github.io/ml-teaching/notebooks/names.html)| |
26| 11 March| [Mock Quiz](https://nipunbatra.github.io/ml-teaching/slides/mock-quiz-2.pdf)| |[Solution](https://nipunbatra.github.io/ml-teaching/slides/mock-quiz-2-solution.pdf)| |
27| 13 March| [Autograd](https://nipunbatra.github.io/ml-teaching/slides/autograd.pdf)|[Recording](https://www.youtube.com/watch?v=Qo3z51lBQ1k)|[Notebook](https://nipunbatra.github.io/ml-teaching/notebooks/autodiff.html)| |
28| 18 March| [CNN - I](https://nipunbatra.github.io/ml-teaching/slides/CNN.pdf), [1D CNN](https://nipunbatra.github.io/ml-teaching/slides/1d-cnn.pdf) |[Recording](https://www.youtube.com/watch?v=CfC3hOYSTNc)|[Notebook 1](https://nipunbatra.github.io/ml-teaching/notebooks/1d-cnn.html), [Notebook 2 on edge detection](https://nipunbatra.github.io/ml-teaching/notebooks/cnn-edge.html), [Notebook 3 on LeNet](https://nipunbatra.github.io/ml-teaching/notebooks/cnn.html)| |
29| 20 March| [CNN - II](https://nipunbatra.github.io/ml-teaching/slides/CNN.pdf) |[Recording](https://www.youtube.com/watch?v=tZJwzURBinE)|[Notebook]()| |
30| 22 March| [KNN](https://nipunbatra.github.io/ml-teaching/slides/knn.pdf) |[Recording](https://www.youtube.com/watch?v=hwwl_M-emaY)|[Notebook (Parametric v/s Non-Parametric)](https://nipunbatra.github.io/ml2023/notebooks/posts/parametric-non-parametric.html), [Notebook (Curse of dimensionality)](https://nipunbatra.github.io/ml-teaching/notebooks/curse-dimensionality)| Reference on Parameteric v/s Non-Parametric [from MLSS](http://mlss.tuebingen.mpg.de/2015/slides/ghahramani/gp-neural-nets15.pdf), [ML Mastery](https://machinelearningmastery.com/parametric-and-nonparametric-machine-learning-algorithms/), [StackExchange](https://stats.stackexchange.com/questions/268638/what-exactly-is-the-difference-between-a-parametric-and-non-parametric-model), [Sebastian Raschka's blog](https://sebastianraschka.com/faq/docs/parametric_vs_nonparametric.html) |
31| 1 April| [Reinforcement learning](https://nipunbatra.github.io/ml-teaching/slides/rl.pdf) |[Recording](https://www.youtube.com/watch?v=Gth666ecEYM)|[Notebook 1](https://nipunbatra.github.io/ml-teaching/notebooks/rl-1.html), [Notebook 2](https://nipunbatra.github.io/ml-teaching/notebooks/rl-2.html)| |
32| 3 April| [Unsupervised learning](https://nipunbatra.github.io/ml-teaching/slides/unsupervised.pdf)|[Recording](https://www.youtube.com/watch?v=Zoubg9Gvq40)|[Notebook]()| |
33| 5 April| [Approximate KNN](https://nipunbatra.github.io/ml-teaching/slides/KNN-approx.pdf)| [Recording](https://www.youtube.com/watch?v=C9HQLyXwEw0)|[Notebook](https://nipunbatra.github.io/ml-teaching/notebooks/knn-variants.html)| |
34| 8 April| [Constrained Optimization 1](https://nipunbatra.github.io/ml-teaching/slides/constrained-1.pdf), [Constrained Optimization 2 (self study)](https://nipunbatra.github.io/ml-teaching/slides/constrained-2.pdf)| [Part 2 recording from older run](https://www.youtube.com/watch?v=Gr1o97QI1PI)|[Notebook]()| |
35| 10 April| [SVM - I](https://nipunbatra.github.io/ml-teaching/slides/svm-intro.pdf)|[Recording](https://www.youtube.com/watch?v=GJ79bHF1P5I)|[Notebook 1](https://nipunbatra.github.io/ml-teaching/notebooks/svm.html)| |
36| 12 April| [SVM - II (Kernel)](https://nipunbatra.github.io/ml-teaching/slides/svm-intro.pdf)|[Recording](https://www.youtube.com/watch?v=evGchl_3pGY&list=PLftoLyLEwECDqanAL7LkZNnZG9VdNCiJF&index=30)|[Notebook](https://nipunbatra.github.io/ml-teaching/notebooks/svm-primal-dual.html), [Notebook 2](https://nipunbatra.github.io/ml-teaching/notebooks/svm-kernel.html)| |
37| 15 April| SVM - III (QP, Kernels as similarity)|[Recording](https://www.youtube.com/watch?v=BLj0hhT-tL4)|[Notebook on QP](https://nipunbatra.github.io/ml-teaching/notebooks/svm-cvxopt.html), [Notebook on kernels-1](https://nipunbatra.github.io/ml-teaching/notebooks/svm-kernel-understanding.html)| |    
38| 17 April| [SVM - IV (Kernel understanding, Soft Margin)](https://nipunbatra.github.io/ml-teaching/slides/svm-soft-margin.pdf)|[Recording](https://www.youtube.com/watch?v=QaYpHAc5N-A&list=PLftoLyLEwECDqanAL7LkZNnZG9VdNCiJF&index=32)|[Notebook on kernel understanding](https://nipunbatra.github.io/ml-teaching/notebooks/svm-kernel.html), [Notebook on soft margin](https://nipunbatra.github.io/ml-teaching/notebooks/svm-soft-margin.html)| |
39| 19 April| Overall revision|
<!--
27| 18 March| [Naive Bayes]| [Recording]()|[Notebook]()| |
28| 20 March| [KNN] |[Recording]()|[Notebook]()| |
29| 1 April| [Unsupervised Learning - 1] |[Recording]()|[Notebook]()| |
30|3 April | [Unsupervised Learning - 2] |[Recording]()|[Notebook]()| |
31| 5 April| [Constrained Optimization] |[Recording]()|[Notebook]()| |
32| 8 April| [SVM - 1] |[Recording]()|[Notebook]()| |
33| 10 April| [SVM - 2] |[Recording]()|[Notebook]()| |
34| 12 April| [SVM - 3] |[Recording]()|[Notebook]()| |
35| 15 April| [RL - 1] |[Recording]()|[Notebook]()| |
36| 17 April| [RL - 2] |[Recording]()|[Notebook]()| |
37| 19 April| [Mock Quiz] |[Recording]()|[Notebook]()| |




|None| 4 Jan|[Pre-requisites quiz released](https://nipunbatra.github.io/ml2023/exams/prereq.html)|
|2|5 Jan|Convention, Metrics, Classification, Regression [[Slides](lectures/accuracy.pdf)]|
|3|10 Jan|Decision Trees - 1[[Slides](lectures/decision-tree-1.pdf)][[Notebook](https://nipunbatra.github.io/ml2023/notebooks/posts/tips.html)]|
|4|12 Jan|Decision Trees - 2[[Slides](lectures/decision-tree-2-bias-variance-1.pdf)][[Notebook](https://nipunbatra.github.io/ml2023/notebooks/posts/pivot-cross.html)]|
|5|17 Jan|Bias and Variance[[Slides](lectures/bias-variance-1.pdf)][[Notebook on Python utils](https://nipunbatra.github.io/ml2023/notebooks/posts/python-utils.html)][[Notebook on Grid Search](https://nipunbatra.github.io/ml2023/notebooks/posts/hyperparameter-1.html)]|
|None| 18 Jan| Quiz 1|
|6|19 Jan| Bias, Variance 2, Cross Validation[[Slides](lectures/cross-validation.pdf)]|
|7|24 Jan| Ensemble Methods[[Slides](lectures/ensemble.pdf)]| 
|8|31 Jan| Ensemble Methods[[Slides](lectures/ensemble.pdf)], Weighted samples in decision trees[[Slides](lectures/dt-weighted.pdf)], Maths for ML-1 [[Slides](lectures/ml-maths.pdf)] [[Notebook-1](https://nipunbatra.github.io/ml2023/notebooks/posts/maths-jax.html)] [[Notebook 2](https://nipunbatra.github.io/ml2023/notebooks/posts/lowrank-matrix.html)], [[Streamlit app](notebooks/posts/streamlit-app.py)] Linear Regression [[Slides](lectures/linear-regression.pdf)]|
|9| 2 Feb| Linear Regression [[Slides](lectures/linear-regression.pdf)], Contour Plots [[Slides](lectures/ml-maths-2-contour.pdf)], Geometric View of Linear Regression [[Slides](lectures/geometric-regression.pdf)]|
|10| 9 Feb| Linear Regression II [[Slides](lectures/linear-regression-2.pdf)]|
|11| 14 Feb| Gradient Descent [[Slides](lectures/Gradient-descent.pdf)], [Taylor's Series](https://www.youtube.com/watch?v=3d6DsjIBzJ4&t), [Notebook on Taylor's series](https://nipunbatra.github.io/ml2023/notebooks/posts/taylor.html), [Reference on relationship between Taylor's series and GD](https://www.cs.princeton.edu/courses/archive/fall18/cos597G/lecnotes/lecture3.pdf), [Reference 2](https://ekamperi.github.io/machine%20learning/2019/07/28/gradient-descent.html)|
|12| 16 Feb| Gradient Descent [[Slides](lectures/Gradient-descent.pdf)] [Notebook](https://nipunbatra.github.io/ml2023/notebooks/posts/gd.html)|
|13| 21 Feb|Gradient Descent continued, [[Ridge Regression](lectures/ridge-regression.pdf)], [[Streamlit demo](https://nipunbatra-ml-ridge.streamlit.app)], [[Additional reading on SGD being an unbiased estimator](https://florian.github.io/estimators/)]|
|14| 23 Feb|Ridge regression, [LASSO](lectures/lasso-regression.pdf), [[Interactive article on Optimization algorithms](https://fa.bianp.net/teaching/2018/COMP-652/stochastic_gradient.html)]|
|15| 28 Feb|Logistic regression [[Slides](lectures/logistic-1.pdf)], [[Notebook](https://nipunbatra.github.io/ml2023/notebooks/posts/logistic.html)] (best run locally to render interactive visualisations)|
|16| 2 Mar|Logistic regression [[Slides](lectures/logistic-1.pdf)]|
|17| 14 Mar| Logistic regression [[Slides](lectures/logistic-1.pdf)]|
|18| 16 Mar| MLP [[Slides](lectures/mlp.pdf)]|
|19| 21 Mar| MLP [[Slides](lectures/mlp.pdf)], [Notebook](https://nipunbatra.github.io/ml2023/notebooks/posts/nn.html)|
|20| 28 Mar| MLP [[Slides](lectures/mlp.pdf)]|
|21| 30 Mar| Next work prediction [[Slides](lectures/next-token.pdf)], [Notebook](https://nipunbatra.github.io/ml2023/notebooks/posts/names.html)|
|22| 4 Apr | Convolutional Neural Networks [[Slides](lectures/CNN.pdf)], [1d CNN slides](lectures/1d-cnn.pdf), [Notebook 1](https://nipunbatra.github.io/ml2023/notebooks/posts/cnn.html), [Notebook 2](https://nipunbatra.github.io/ml2023/notebooks/posts/cnn-edge.html), [Notebook 3](https://nipunbatra.github.io/ml2023/notebooks/posts/1d-cnn.html), [Equivariance v/s Invariance](https://www.doc.ic.ac.uk/~bkainz/teaching/DL/notes/equivariance.pdf), [Reference1](https://poloclub.github.io/cnn-explainer/), [Reference2](https://e2eml.school/how_convolutional_neural_networks_work.html), [Notebook](https://nipunbatra.github.io/ml2023/notebooks/posts/cnn.html)|
|23| 6 Apr| Autograd  [[Slides](lectures/autograd.pdf)], [Notebook on Autodiff](https://nipunbatra.github.io/ml2023/notebooks/posts/autodiff-helper.html), [Reference on chain rule](https://tutorial.math.lamar.edu/classes/calciii/chainrule.aspx) Naive Bayes [[Slides](lectures/naive-bayes.pdf)]|
|24| 11 Apr| Naive Bayes [[Slides](lectures/naive-bayes.pdf)], KNN [[Slides](lectures/knn.pdf)]|
|25| 13 Apr| KNN, [Parametric v/s Non-Parametric](https://nipunbatra.github.io/ml2023/notebooks/posts/parametric-non-parametric.html), [Movie Recommendation](https://nipunbatra.github.io/ml2023/notebooks/posts/movie-recommendation-knn-mf.html)|
|26| 18 Apr| [Curse of Dimensionality](https://nipunbatra.github.io/ml2023/notebooks/posts/curse-dimensionality.html), [Segment Anything demo](https://segment-anything.com), Unsupervised learning, [Image segmentation](https://nipunbatra.github.io/ml2023/notebooks/posts/kmeans-segmentation.html), [Image completion](https://nipunbatra.github.io/ml2023/notebooks/posts/image-completion.html), KMeans [Viz 1](https://www.naftaliharris.com/blog/visualizing-k-means-clustering/), [Viz 2](http://alekseynp.com/viz/k-means.html), [PCA reference](https://www.youtube.com/watch?v=g-Hb26agBFg)|
|27| 20 Apr| [Constrained Optimization (self study)](https://www.youtube.com/watch?v=rjq0g-ugwwg), [Support Vector Machines -1](lectures/svm-intro.pdf)|
|28| 23 Apr| [Support Vector Machines](lectures/svm-intro.pdf)|
|29| 25 Apr| [Support Vector Machines (Soft Margin)](lectures/svm-soft-margin.pdf)|


-->

